# Generated by Django 5.1.4 on 2026-07-16 16:00

import activities.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='titel')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('date', models.DateField(verbose_name='datum')),
                ('time_text', models.CharField(blank=True, help_text='Bijv. "21:00" of "12:00–18:00, BBQ 18:00"', max_length=120, verbose_name='tijd')),
                ('theme', models.CharField(blank=True, help_text='Bijv. "Piraten & Zeemeerminnen"', max_length=120, verbose_name='thema')),
                ('location_text', models.CharField(blank=True, help_text='Bijv. "Het Bastion" of "Villa van Schaeck"', max_length=140, verbose_name='locatie')),
                ('description', models.TextField(blank=True, help_text='Markdown toegestaan.', verbose_name='beschrijving')),
                ('image', models.ImageField(blank=True, upload_to='activities/', verbose_name='afbeelding')),
                ('cost_note', models.CharField(blank=True, help_text='Betaling ter plekke, dit is alleen een opmerking.', max_length=120, verbose_name='kosten')),
                ('requires_registration', models.BooleanField(default=True, help_text='Uit = "kom gewoon langs", geen inschrijfformulier.', verbose_name='inschrijving vereist')),
                ('external_registration_url', models.URLField(blank=True, help_text='Bijv. een bestaand Google Form of WAZ-link.', verbose_name='externe inschrijflink')),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Leeg = onbeperkt.', null=True, verbose_name='capaciteit')),
                ('registration_opens_at', models.DateTimeField(blank=True, null=True, verbose_name='inschrijving opent')),
                ('registration_closes_at', models.DateTimeField(blank=True, null=True, verbose_name='inschrijving sluit')),
                ('collect_phone', models.BooleanField(default=True, verbose_name='telefoonnummer vragen')),
                ('collect_study', models.BooleanField(default=True, verbose_name='studie vragen')),
                ('collect_dietary', models.BooleanField(default=True, help_text='Wordt alleen gevraagd t.b.v. de catering.', verbose_name='dieetwensen vragen')),
                ('custom_fields', models.JSONField(blank=True, default=list, help_text='Lijst met velden, bijv.: [{"key": "tshirt_maat", "label": "T-shirt maat", "type": "select", "required": false, "options": ["S", "M", "L", "XL"]}]. type is een van: text, textarea, select, checkbox, number.', validators=[activities.models.validate_custom_fields], verbose_name='aangepaste velden')),
                ('is_published', models.BooleanField(default=False, verbose_name='gepubliceerd')),
                ('sort_order', models.IntegerField(default=0, verbose_name='volgorde')),
            ],
            options={
                'verbose_name': 'activiteit',
                'verbose_name_plural': 'activiteiten',
                'ordering': ['sort_order', 'date'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='naam')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mailadres')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='telefoonnummer')),
                ('study', models.CharField(blank=True, max_length=140, verbose_name='studie')),
                ('dietary', models.CharField(blank=True, max_length=255, verbose_name='dieetwensen')),
                ('answers', models.JSONField(blank=True, default=dict, verbose_name='antwoorden aangepaste velden')),
                ('status', models.CharField(choices=[('confirmed', 'Bevestigd'), ('waitlist', 'Wachtlijst'), ('cancelled', 'Geannuleerd')], max_length=12, verbose_name='status')),
                ('consent', models.BooleanField(default=False, verbose_name='toestemming gegeven')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='aangemaakt op')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='activities.activity', verbose_name='activiteit')),
            ],
            options={
                'verbose_name': 'inschrijving',
                'verbose_name_plural': 'inschrijvingen',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'cancelled'), _negated=True), fields=('activity', 'email'), name='uniq_active_email_per_activity')],
            },
        ),
    ]
