# Generated by Django 5.1.4 on 2026-07-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='video_url',
            field=models.URLField(blank=True, help_text='Instagram- of YouTube-link; wordt als video op de kaart getoond.', verbose_name='promotievideo'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(blank=True, help_text="Leeg laten voor een 'nog aan te kondigen' activiteit.", null=True, verbose_name='datum'),
        ),
    ]
